(function() {

  module.exports = function(createjs) {
    var circle, stage;
    stage = new createjs.Stage('main');
    circle = new createjs.Shape();
    circle.graphics.beginFill('red').drawCircle(0, 0, 10);
    circle.x = circle.y = 100;
    stage.addChild(circle);
    return stage.update();
  };

}).call(this);

// Generated by CoffeeScript 1.5.0-pre
