(function() {

  oCanvas.domReady(function() {
    var canvas;
    return canvas = oCanvas.create({
      canvas: '#main',
      background: '#222'
    });
  });

}).call(this);

// Generated by CoffeeScript 1.5.0-pre
